/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#fff7f6",
        "tertiary-fixed-dim": "#ece4df",
        "tertiary": "#635e5a",
        "surface-tint": "#735a3a",
        "on-surface": "#31332c",
        "secondary": "#735b3a",
        "outline-variant": "#b1b3a9",
        "on-secondary": "#fff8f2",
        "background": "#fbf9f4",
        "on-secondary-fixed": "#503c1d",
        "on-primary-fixed-variant": "#705738",
        "inverse-on-surface": "#9e9d99",
        "surface-container-low": "#f5f4ed",
        "primary": "#735a3a",
        "on-primary": "#fff6f0",
        "on-primary-fixed": "#513b1e",
        "error-container": "#fe8b70",
        "surface-container-highest": "#e2e3d9",
        "secondary-fixed": "#feddb3",
        "error": "#9e422c",
        "on-tertiary-fixed-variant": "#6b6561",
        "secondary-dim": "#664f2f",
        "on-secondary-container": "#644e2e",
        "primary-fixed": "#ffddb6",
        "secondary-container": "#feddb3",
        "surface-bright": "#fbf9f4",
        "outline": "#797c73",
        "error-dim": "#5c1202",
        "on-primary-container": "#654d2f",
        "on-error-container": "#742410",
        "on-surface-variant": "#5e6058",
        "secondary-fixed-dim": "#efd0a6",
        "primary-container": "#ffddb6",
        "surface-variant": "#e2e3d9",
        "tertiary-fixed": "#fbf2ed",
        "primary-dim": "#664e30",
        "inverse-primary": "#fddab2",
        "on-background": "#31332c",
        "surface-container": "#efeee6",
        "on-tertiary-container": "#605b57",
        "on-tertiary-fixed": "#4e4945",
        "surface-container-high": "#e8e9e0",
        "tertiary-dim": "#57524f",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#0e0e0c",
        "primary-fixed-dim": "#f1cfa8",
        "tertiary-container": "#fbf2ed",
        "surface": "#fbf9f4",
        "on-secondary-fixed-variant": "#6f5836",
        "on-tertiary": "#fff7f4",
        "surface-dim": "#d9dbcf"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
